### ISSUE TITLE
Cache inputs: ignore subfolder

### ISSUE THREAD

**Issue by CoenWarmer** [bitrise-steplib/steps-cache-push#28]
I would like to include a certain folder in my cache archive, but exclude a certain subfolder of that folder. Am I correct in assuming this works by prefixing a certain path with `!`?

Example:
```
      - cache-push:
          inputs:
            - cache_paths: |-
                $HOME/.gradle
                ./.gradle
                ./npm
                ./plugins
				./platforms
				!./platforms/ios/build/device . # Exclude this subfolder from cache? 
            - ignore_check_on_paths: |-
                $HOME/.gradle/caches/*.lock
                ./.gradle/*.lock
                ./.gradle/*.bin
```

**Comment by fehersanyi-bitrise** [comment]
Hy there, you are correct, it will be ignored with the `!` prefix, although it might not work just like this🤔
well if it does that is good, but if not then I think you should define the subfolders dependently maybe.
