### ISSUE TITLE
Why does this step ignore android build cache?

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-cache-push#37]
```
+------------------------------------------------------------------------------+
| (12) cache-push                                                              |
+------------------------------------------------------------------------------+
| id: cache-push                                                               |
| version: 2.2.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-01-06T20:59:48Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
[36mINFO[0m[20:59:48] Start installing (tar) with apt-get          
[36mINFO[0m[20:59:48]  * [32;1m[OK][0m Step dependency (tar) installed, available. 
[34;1mConfig:
[0m- Paths: /bitrise/cache


/root/.gradle -> /bitrise/src/gradle.deps
/root/.kotlin -> /bitrise/src/gradle.deps
/root/.m2 -> /bitrise/src/gradle.deps

- IgnoredPaths: 

~/.gradle/**
~/.android/build-cache/** <----- HERE
*.lock
*.bin
*/build/*.json
*/build/*.html
*/build/*.xml
*/build/*.properties
*/build/*/zip-cache/*
*.log
*.txt
*.rawproto
!*.ap_
!*.apk
```

**Comment by non-binary** [comment]
Hi @tir38,

Thank you for reaching out.

Can you please share a link to a build demonstrating this issue (or share a full build log and the associated bitrise.yml file used for the build)?

Thanks and looking forward to hearing from you.

Kind regards,
Luna

**Comment by tir38** [comment]
@non-binary https://app.bitrise.io/build/08527a1fd2cbbdd4#?tab=log 
LMK if i need to enable Bitrise Support User.

**Comment by non-binary** [comment]
@tir38 Thanks for the link. It was enough for me to access the log and yaml. I will investigate further and follow-up soon once I have determined what the issue was. Cheers

**Comment by non-binary** [comment]
Hi @tir38,

Thank you for your patience.

It seems you are using the default configuration for the caching step, which is why this directory is ignored. From my understanding, not everyone wants to cache that so it is ignored by default. To include it in the caching step add the following:

```yml
- cache-push:
      inputs:
      - cache_paths: |-
          ~/.android/build-cache/**
```

Please don't hesitate to follow-up if you have any other questions.

Kind regards,
Luna

**Comment by tir38** [comment]
I recently learned that Android doesn't use this cache directory any more (but oddly still creates it) So that might explain why people default to ignoring it: it's just an empty directory.
