### ISSUE TITLE
Working directory path doesn't seem to be used anywhere

### ISSUE THREAD

**Issue by fcamblor** [bitrise-steplib/steps-cache-push#54]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.5.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? DUNNO

### Issue description

When playing with the Cache Push step, I discovered that the `workdir` step configuration was not taken into consideration during paths resolution.

For example, when defining : 

```
workdir: $SUBMODULE_PATH
cache_paths : 
./node_modules/ -> ./package.json
```

To make it work, I had to replace it with :
```
workdir: $SUBMODULE_PATH
cache_paths : 
$SUBMODULE_PATH/node_modules/ -> $SUBMODULE_PATH/package.json
```

Looking at the source code of this repository, I didn't found any usage of `workdir` in Go scripts, which seems to corroborate this assumption.

### Bitrise info

- Build URL: https://app.bitrise.io/app/96c83739fc8bc51a/workflow_editor#!/workflows?workflow_id=testing-caches
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: https://app.bitrise.io/build/b0b6fd1999e5498f#?tab=log

<details>
  <pre>
Config:
- Paths: ./test/ -> ./test.json
haulier-mobile/node_modules/ -> haulier-mobile/package.json
- IgnoredPaths: 
- CacheAPIURL: [REDACTED]
- FingerprintMethodID: file-content-hash
- CompressArchive: false
- DebugMode: true
- StackID: osx-xcode-12.4.x
- BuildSlug: 49ea7c4aea1089cf
Cleaning paths
indicator does not exists at: /Users/vagrant/git/test.json
Done in 285.461µs
Checking previous cache status
No previous cache info found
Done in 137.048µs
Generating cache archive
Done in 1.154183ms
Uploading cache archive
Archive file size: 4608 bytes / 0.004395 MB
Done in 608.697903ms
Total time: 610.628844ms
  </pre>
</details>

### Steps to reproduce

Create a workflow with following steps : 
- Git clone
- Cache Pull with some working directory
- Cache Push with some working directory, and with following variabilized cache paths : 
```
./test/ -> ./test.json
$CORDOVA_WORK_DIR/node_modules/ -> $CORDOVA_WORK_DIR/package.json
```

By looking at build log, we can see that when `workdir` is not used, bitrise doesn't synchronizes anything : 
```
Cleaning paths
indicator does not exists at: /Users/vagrant/git/test.json
Done in 285.461µs
Checking previous cache status
No previous cache info found
Done in 137.048µs
Generating cache archive
Done in 1.154183ms
```
=> it tries to synchronize `test.json` from git root, instead of `$CORDOVA_WORK_DIR`

**Comment by Roland-Bak** [comment]
Hello there @fcamblor 👋

Thanks for the info!

The default input for workdir is $BITRISE_SOURCE_DIR, could you let me know if that worked for you originally?
