### ISSUE TITLE
Step doesn't execute glob matches on the Cache Paths input

### ISSUE THREAD

**Issue by rogerluan** [bitrise-steplib/steps-cache-push#55]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.5.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

After reading [the Caching guide](https://devcenter.bitrise.io/builds/caching/about-caching-index/), I realized that there is glob matching for paths, but apparently this only works when excluding paths, not when including them. I could not make glob work with path inclusion. I tried many different variations of globs, with and without quotes around them, and none worked. Here's an example:

Input:
```
"**/Pods"
"**/.vendor"
"**/.build"
"**/.swiftpm"
```

Result:

```
Cleaning paths
path does not exists at: /Users/vagrant/git/"**/Pods"
path does not exists at: /Users/vagrant/git/"**/.vendor"
path does not exists at: /Users/vagrant/git/"**/.build"
path does not exists at: /Users/vagrant/git/"**/.swiftpm"
Done in 210.622µs
```

I tried without quotes, with */**/path, with trailing slash, none of those options work.

After code reviewing this repository, I noticed that the glob matching indeed is only executed when excluding paths (AFAICT - I'm not familiar with Golang 😬 )

### Bitrise info

- Build URL: N/A
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log:

<details>
  <pre>
Cleaning paths
path does not exists at: /Users/vagrant/git/"**/Pods"
path does not exists at: /Users/vagrant/git/"**/.vendor"
path does not exists at: /Users/vagrant/git/"**/.build"
path does not exists at: /Users/vagrant/git/"**/.swiftpm"
Done in 210.622µs
  </pre>
</details>

### Steps to reproduce

1. Have a project with multiple levels of directories (2+)
2. Try matching those directories to be cached using glob, using `*`, `**` and `/`. You can try debugging glob using https://www.digitalocean.com/community/tools/glob
3. Watch this Step not find the specified path

**Comment by lpusok** [comment]
Hello @rogerluan,
You can specify relative paths but not globs right now, like `./Pods`. Environment variables are also expanded in the include paths.

**Comment by rogerluan** [comment]
Thanks for the prompt response @lpusok! Is there a time horizon for this feature to be implemented? 

I guess I can script my way using env vars, but ideally the glob match should happen (it's only intuitive) 🙏

**Comment by mateherber** [comment]
Hi @rogerluan,

Please look at version `2.6.0` of the step that should support glob matches.

**Comment by rogerluan** [comment]
Thank you @mateherber . By now I've already changed my project structure to allow for easier caching 😅 but it's good to know there's this option now, it will certainly help a lot of users. 🙏
